version: '3.6'

volumes:
  postgres_data:

services:

  web:

    build: .
    command: python UNIVERSITY/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  redis:
    image: "redis:latest"

  celery:
    build: .
    working_dir: /code/UNIVERSITY
    command: celery -A UNIVERSITY worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis
  celery-beat:
    build: .
    working_dir: /code/UNIVERSITY
    command: celery -A UNIVERSITY beat -l info
    volumes:
      - .:/code
    depends_on:
      - redis

  db:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Roma
      - POSTGRES_DB=University
